Recommended materials:

[pytorch official doc](https://pytorch.ac.cn/docs/stable/torch.html)

In [1]:
# import all modules
import torch
import numpy as np

In [9]:
#useful functions to create tensor
aDirect=torch.tensor([1,2,3]) #directly create
aZero=torch.zeros(2,3)  #shape(2,3)
bOne=torch.ones(4)     #shape(4,)
cFull=torch.full((2,2),7)   #shape(2,2)with7
aRand=torch.rand(3,3)   #obey uniform distribution[0,1)with shape (3,3)
bRand=torch.randn(3,3)  #obey standard formal distribution with shape(3,3)
cRand=torch.empty(2,2).uniform_(2,5)    #obey uniform distribution[2,5) with shape (2,2)
dRand=torch.empty(2,2).normal_(mean=1,std=2)    #obey formal distribution with shape (2,2)
aRange=torch.arange(0,10,2)  #create a tensor with range [0,10) with step 2
bRange=torch.linspace(0,10,5)  #create a tensor with range [0,10] with 5 points

arr=np.array([[1,2,3],[4,5,6]])  #create a numpy array
aNumpy=torch.from_numpy(arr)  #convert numpy array to tensor
aShape=torch.zeros_like(aNumpy)  #create a tensor with the same shape as aNumpy
bShape=torch.ones_like(aNumpy)  #create a tensor with the same shape as aNumpy

a = torch.zeros((2, 2), dtype=torch.float32, device='cpu')
b = torch.ones((2, 2), dtype=torch.int64, device='cuda')
     

In [13]:
#useful functions to operate tensor
print(a.shape)  #shape
print(a.numel())    #number of elements
print(a.dim())  #number of dimensions
print(a.dtype)  #data type
a=a.to(torch.int64)  #change data type to int64
print(a.dtype)  #data type
y=a.view(-1,4)  #change shape to (-1,4), -1 means automatically calculate the number of rows
x = torch.randn(2, 3, 4)
z = x.flatten(start_dim=1)      # connect dimmension from 1 to the end
print(z.shape)  #shape
w=x.permute(2,0,1)  #change the order of dimensions, (2,0,1) means the first dimension becomes the third dimension, the second dimension becomes the first dimension, and the third dimension becomes the second dimension
print(w.shape)  #shape
x   = torch.randn(4, 3, 5, 5)      # (N=4, C=3, H=5, W=5)
idx = torch.tensor([0, 2])         # kepp 0,2 channels
row = torch.index_select(x, dim=1, index=idx)
print(row.shape)    # -> (4, 2, 5, 5)

torch.Size([2, 2])
4
2
torch.int64
torch.int64
torch.Size([2, 12])
torch.Size([4, 2, 3])
torch.Size([4, 2, 5, 5])


In [16]:
#split tensor
# Two sample tensors of shape (3, 4)
a = torch.arange(12).reshape(3, 4)
b = torch.arange(100, 112).reshape(3, 4)

# --------------------------
# 1) torch.cat – concatenate along an existing dimension
#    Here: dim=0 (row-wise), shape becomes (6, 4)
# --------------------------
cat_result = torch.cat([a, b], dim=0)
print("cat_result.shape:", cat_result.shape)


# --------------------------
# 2) torch.stack – create a new dimension and stack tensors
#    Here: dim=0 ⇒ new leading axis, shape becomes (2, 3, 4)
# --------------------------
stack_result = torch.stack([a, b], dim=0)
print("\nstack_result.shape:", stack_result.shape)


# --------------------------
# Prepare a tensor for splitting: shape (4, 6)
# --------------------------
x = torch.arange(24).reshape(4, 6)

# 3) torch.chunk – evenly split into N chunks along dim
#    Here: 2 chunks along dim=0 → each chunk has shape (2, 6)
chunks = torch.chunk(x, chunks=2, dim=0)
print("\nchunk shapes:", [c.shape for c in chunks])


# 4) torch.split – split by explicit lengths
#    Here: lengths [1, 2, 3] along dim=1
#    Shapes become (4,1), (4,2), (4,3)
splits = torch.split(x, [1, 2, 3], dim=1)
print("\nsplit shapes:", [s.shape for s in splits])
for i, part in enumerate(splits):
    print(f"split[{i}]:\n", part)

cat_result.shape: torch.Size([6, 4])

stack_result.shape: torch.Size([2, 3, 4])

chunk shapes: [torch.Size([2, 6]), torch.Size([2, 6])]

split shapes: [torch.Size([4, 1]), torch.Size([4, 2]), torch.Size([4, 3])]
split[0]:
 tensor([[ 0],
        [ 6],
        [12],
        [18]])
split[1]:
 tensor([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]])
split[2]:
 tensor([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])
